const TEMPLATE_RU_TITLES: Record<string, string> = {
  podcast: "Подкаст",
  "center-stage": "Эксперт в кадре",
  "podcast-countdown": "Подкаст с дедлайном",
  "simple-text": "Кино-титр",
  whiteboard: "Доска с разбором",
  "text-on-image": "Большой текст поверх фото",
  history: "Две реальности",
  explainer: "Карточка с цифрой",
  "object-in-hand": "Предмет в руках",
  "contextual-background": "Сюжетный фон",
  "before-after": "До/после",
  "multi-pov": "Мульти-POV",
  notifications: "Уведомления",
  "brain-rot-podcast": "Подкаст Brain Rot",
  "gaming-card": "Игровая карточка",
  "story-cards": "Карточки историй",
  "floating-proof": "Доказательство с цифрой",
  educational: "Обучающий график",
  "vertical-timeline": "Таймлайн",
  "vertical-podcast": "Вертикальный подкаст",
  "holding-card": "Карточка в руках",
  "vertical-background": "Большой фон",
  "vertical-simple-text": "Простой текст",
  "vertical-3d-interface": "3D-интерфейс",
  "kling-2-6": "Kling 2.6",
  "action-scene": "Экшен-сцена",
  "laying-down": "Съемка сверху",
  "big-action": "Большое действие",
  "floating-object": "Парящий объект",
  "background-split": "Фон с интерфейсом",
  "vertical-object-in-hand": "Предмет в руках",
  "faceless-pov": "POV без лица",
  "foreground-focus": "Объект на первом плане",
  "center-object-text": "Объект в центре",
  "split-compare": "Сравнение до/после"
};

export function templateDisplayName(slug: string, fallbackTitle: string) {
  return TEMPLATE_RU_TITLES[slug] ?? fallbackTitle;
}
